// 种子数据：开箱即用的初始库存、食谱库与偏好
// 日期使用相对计算，便于演示保质期效果

function dateOffset(days) {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export const SEED_INVENTORY = [
  // —— 食材：蔬菜 ——
  { id: 'ing_001', name: '番茄',     category: 'ingredient', subcategory: '蔬菜', quantity: 4,   unit: '个',  purchaseDate: dateOffset(-2), expiryDate: dateOffset(3),  tags: ['清淡'],  note: '' },
  { id: 'ing_002', name: '鸡蛋',     category: 'ingredient', subcategory: '蛋类', quantity: 10,  unit: '个',  purchaseDate: dateOffset(-5), expiryDate: dateOffset(15), tags: ['高蛋白'], note: '' },
  { id: 'ing_003', name: '土豆',     category: 'ingredient', subcategory: '蔬菜', quantity: 500, unit: 'g',   purchaseDate: dateOffset(-7), expiryDate: dateOffset(20), tags: ['主食替代'], note: '' },
  { id: 'ing_004', name: '鸡胸肉',   category: 'ingredient', subcategory: '肉类', quantity: 300, unit: 'g',   purchaseDate: dateOffset(-1), expiryDate: dateOffset(2),  tags: ['高蛋白'], note: '即将到期' },
  { id: 'ing_005', name: '西兰花',   category: 'ingredient', subcategory: '蔬菜', quantity: 1,   unit: '颗',  purchaseDate: dateOffset(-3), expiryDate: dateOffset(4),  tags: ['清淡'],  note: '' },
  { id: 'ing_006', name: '胡萝卜',   category: 'ingredient', subcategory: '蔬菜', quantity: 3,   unit: '根',  purchaseDate: dateOffset(-4), expiryDate: dateOffset(12), tags: [],        note: '' },
  { id: 'ing_007', name: '洋葱',     category: 'ingredient', subcategory: '蔬菜', quantity: 2,   unit: '个',  purchaseDate: dateOffset(-6), expiryDate: dateOffset(18), tags: [],        note: '' },
  { id: 'ing_008', name: '北豆腐',   category: 'ingredient', subcategory: '豆制品', quantity: 1, unit: '块',  purchaseDate: dateOffset(-1), expiryDate: dateOffset(5),  tags: ['素食'],  note: '' },
  { id: 'ing_009', name: '虾',       category: 'ingredient', subcategory: '水产', quantity: 200, unit: 'g',   purchaseDate: dateOffset(-2), expiryDate: dateOffset(1),  tags: ['高蛋白'], note: '尽快食用' },
  { id: 'ing_010', name: '卷心菜',   category: 'ingredient', subcategory: '蔬菜', quantity: 0.5, unit: '颗',  purchaseDate: dateOffset(-3), expiryDate: dateOffset(8),  tags: [],        note: '' },
  { id: 'ing_011', name: '挂面',     category: 'ingredient', subcategory: '主食', quantity: 1,   unit: '包',  purchaseDate: dateOffset(-20), expiryDate: dateOffset(180), tags: ['主食'], note: '' },
  { id: 'ing_012', name: '米饭',     category: 'ingredient', subcategory: '主食', quantity: 1,   unit: '锅',  purchaseDate: dateOffset(-1), expiryDate: dateOffset(2),  tags: ['主食'], note: '已煮好' },
  { id: 'ing_013', name: '牛奶',     category: 'ingredient', subcategory: '饮品', quantity: 1,   unit: '盒',  purchaseDate: dateOffset(-2), expiryDate: dateOffset(10), tags: [],        note: '' },
  { id: 'ing_014', name: '黄瓜',     category: 'ingredient', subcategory: '蔬菜', quantity: 2,   unit: '根',  purchaseDate: dateOffset(-1), expiryDate: dateOffset(6),  tags: ['清淡'],  note: '' },

  // —— 调味料 ——
  { id: 'sea_001', name: '生抽',     category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-60), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_002', name: '老抽',     category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-60), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_003', name: '盐',       category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '袋',  purchaseDate: dateOffset(-90), expiryDate: dateOffset(720), tags: [], note: '' },
  { id: 'sea_004', name: '糖',       category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '袋',  purchaseDate: dateOffset(-90), expiryDate: dateOffset(720), tags: [], note: '' },
  { id: 'sea_005', name: '醋',       category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-30), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_006', name: '蚝油',     category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-30), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_007', name: '料酒',     category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-30), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_008', name: '食用油',   category: 'seasoning', subcategory: '常用',   quantity: 1, unit: '桶',  purchaseDate: dateOffset(-30), expiryDate: dateOffset(300), tags: [], note: '' },
  { id: 'sea_009', name: '蒜',       category: 'seasoning', subcategory: '佐料',   quantity: 2, unit: '头',  purchaseDate: dateOffset(-7),  expiryDate: dateOffset(30),  tags: [], note: '' },
  { id: 'sea_010', name: '姜',       category: 'seasoning', subcategory: '佐料',   quantity: 1, unit: '块',  purchaseDate: dateOffset(-7),  expiryDate: dateOffset(30),  tags: [], note: '' },
  { id: 'sea_011', name: '辣椒粉',   category: 'seasoning', subcategory: '佐料',   quantity: 1, unit: '袋',  purchaseDate: dateOffset(-15), expiryDate: dateOffset(300), tags: ['辣'], note: '' },
  { id: 'sea_012', name: '黑胡椒',   category: 'seasoning', subcategory: '佐料',   quantity: 1, unit: '瓶',  purchaseDate: dateOffset(-15), expiryDate: dateOffset(300), tags: [], note: '' },
]

export const SEED_RECIPES = [
  {
    id: 'rec_001',
    name: '番茄炒蛋',
    mealType: 'lunch',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 15,
    calories: 280,
    servings: 2,
    ingredients: [
      { name: '番茄',    quantity: 2,   unit: '个', isMain: true },
      { name: '鸡蛋',    quantity: 3,   unit: '个', isMain: true },
      { name: '盐',      quantity: 2,   unit: 'g',   isMain: false },
      { name: '糖',      quantity: 5,   unit: 'g',   isMain: false },
      { name: '食用油',  quantity: 15,  unit: 'ml',  isMain: false },
    ],
    steps: [
      '番茄切小块，鸡蛋打散加少许盐',
      '热锅冷油，倒入蛋液滑炒至刚凝固盛出',
      '补少量油，下番茄翻炒出汁，加糖提鲜',
      '倒回鸡蛋翻炒均匀即可',
    ],
    tags: ['清淡', '快手', '高蛋白'],
    note: '国民家常菜，老少皆宜',
  },
  {
    id: 'rec_002',
    name: '香煎鸡胸肉',
    mealType: 'lunch',
    cuisine: '西式',
    difficulty: 'easy',
    prepTime: 20,
    calories: 320,
    servings: 1,
    ingredients: [
      { name: '鸡胸肉', quantity: 200, unit: 'g',  isMain: true },
      { name: '黑胡椒', quantity: 2,   unit: 'g',  isMain: false },
      { name: '盐',     quantity: 3,   unit: 'g',  isMain: false },
      { name: '食用油', quantity: 10,  unit: 'ml', isMain: false },
      { name: '生抽',   quantity: 10,  unit: 'ml', isMain: false },
    ],
    steps: [
      '鸡胸肉横切成厚片，加生抽、黑胡椒、盐腌制 10 分钟',
      '热锅下油，中火煎至一面金黄翻面',
      '两面煎约 6 分钟至熟透，静置 2 分钟切片',
    ],
    tags: ['高蛋白', '低脂', '健身'],
    note: '减脂期主力菜',
  },
  {
    id: 'rec_003',
    name: '番茄鸡蛋面',
    mealType: 'breakfast',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 15,
    calories: 380,
    servings: 1,
    ingredients: [
      { name: '挂面',  quantity: 80, unit: 'g', isMain: true },
      { name: '番茄',  quantity: 1,  unit: '个', isMain: true },
      { name: '鸡蛋',  quantity: 1,  unit: '个', isMain: true },
      { name: '盐',    quantity: 2,  unit: 'g', isMain: false },
      { name: '生抽',  quantity: 5,  unit: 'ml', isMain: false },
      { name: '食用油', quantity: 10, unit: 'ml', isMain: false },
    ],
    steps: [
      '番茄切丁，鸡蛋打散',
      '热锅下油炒散鸡蛋，盛出',
      '下番茄炒出汁，加水煮开',
      '下挂面煮熟，加入鸡蛋、调味',
    ],
    tags: ['清淡', '快手', '早餐'],
    note: '简单一顿，搭配牛奶更好',
  },
  {
    id: 'rec_004',
    name: '白灼西兰花',
    mealType: 'dinner',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 10,
    calories: 90,
    servings: 2,
    ingredients: [
      { name: '西兰花', quantity: 1,  unit: '颗', isMain: true },
      { name: '蒜',     quantity: 2, unit: '瓣', isMain: false },
      { name: '盐',     quantity: 2, unit: 'g',  isMain: false },
      { name: '食用油', quantity: 8, unit: 'ml', isMain: false },
      { name: '生抽',   quantity: 8, unit: 'ml', isMain: false },
    ],
    steps: [
      '西兰花掰小朵，淡盐水浸泡 5 分钟',
      '沸水加少许盐和油，焯 1 分钟捞出',
      '热锅爆香蒜末，淋在西兰花上，浇生抽',
    ],
    tags: ['清淡', '素食', '低卡'],
    note: '保留维生素，减脂好搭配',
  },
  {
    id: 'rec_005',
    name: '土豆烧鸡块',
    mealType: 'dinner',
    cuisine: '家常',
    difficulty: 'medium',
    prepTime: 40,
    calories: 420,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', quantity: 200, unit: 'g', isMain: true },
      { name: '土豆',   quantity: 300, unit: 'g', isMain: true },
      { name: '胡萝卜', quantity: 1,   unit: '根', isMain: false },
      { name: '洋葱',   quantity: 0.5, unit: '个', isMain: false },
      { name: '生抽',   quantity: 15,  unit: 'ml', isMain: false },
      { name: '老抽',   quantity: 5,   unit: 'ml', isMain: false },
      { name: '料酒',   quantity: 10,  unit: 'ml', isMain: false },
      { name: '糖',     quantity: 5,   unit: 'g',  isMain: false },
      { name: '姜',     quantity: 3,   unit: '片', isMain: false },
      { name: '食用油', quantity: 15,  unit: 'ml', isMain: false },
    ],
    steps: [
      '鸡肉切块加料酒、生抽腌制 10 分钟',
      '土豆、胡萝卜切滚刀块，洋葱切块',
      '热锅下油，下姜爆香，煎鸡肉至变色',
      '加土豆、胡萝卜、洋葱翻炒，加水没过',
      '加生抽、老抽、糖，小火焖 20 分钟收汁',
    ],
    tags: ['重口', '下饭', '主食替代'],
    note: '一锅出，省事又满足',
  },
  {
    id: 'rec_006',
    name: '麻婆豆腐',
    mealType: 'dinner',
    cuisine: '川菜',
    difficulty: 'medium',
    prepTime: 25,
    calories: 280,
    servings: 2,
    ingredients: [
      { name: '北豆腐', quantity: 1,  unit: '块', isMain: true },
      { name: '辣椒粉', quantity: 5,  unit: 'g',  isMain: false },
      { name: '生抽',   quantity: 10, unit: 'ml', isMain: false },
      { name: '蚝油',   quantity: 5,  unit: 'ml', isMain: false },
      { name: '糖',     quantity: 3,  unit: 'g',  isMain: false },
      { name: '蒜',     quantity: 2,  unit: '瓣', isMain: false },
      { name: '姜',     quantity: 2,  unit: '片', isMain: false },
      { name: '食用油', quantity: 15, unit: 'ml', isMain: false },
    ],
    steps: [
      '豆腐切方块，淡盐水焯 2 分钟去豆腥',
      '热锅下油，爆香姜蒜末，加辣椒粉炒出红油',
      '加水、生抽、蚝油、糖煮开',
      '下豆腐小火煨 8 分钟，勾薄芡出锅',
    ],
    tags: ['麻辣', '重口', '素食'],
    note: '豆腐要轻翻，避免碎',
  },
  {
    id: 'rec_007',
    name: '清炒卷心菜',
    mealType: 'dinner',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 10,
    calories: 110,
    servings: 2,
    ingredients: [
      { name: '卷心菜', quantity: 0.5, unit: '颗', isMain: true },
      { name: '蒜',     quantity: 3,  unit: '瓣', isMain: false },
      { name: '盐',     quantity: 3,  unit: 'g',  isMain: false },
      { name: '食用油', quantity: 12, unit: 'ml', isMain: false },
    ],
    steps: [
      '卷心菜手撕成片，蒜切末',
      '热锅下油爆香蒜末',
      '下卷心菜大火快炒，加盐出锅',
    ],
    tags: ['清淡', '素食', '快手'],
    note: '大火快炒保持脆度',
  },
  {
    id: 'rec_008',
    name: '黄瓜木耳炒鸡蛋',
    mealType: 'breakfast',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 12,
    calories: 220,
    servings: 1,
    ingredients: [
      { name: '鸡蛋',  quantity: 2, unit: '个', isMain: true },
      { name: '黄瓜',  quantity: 1, unit: '根', isMain: true },
      { name: '盐',    quantity: 2, unit: 'g',  isMain: false },
      { name: '食用油', quantity: 10, unit: 'ml', isMain: false },
    ],
    steps: [
      '鸡蛋打散，黄瓜切片',
      '热锅下油炒蛋盛出',
      '下黄瓜翻炒，倒回鸡蛋，加盐调味',
    ],
    tags: ['清淡', '快手', '早餐'],
    note: '清爽开胃',
  },
  {
    id: 'rec_009',
    name: '胡萝卜炒鸡蛋',
    mealType: 'breakfast',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 12,
    calories: 240,
    servings: 1,
    ingredients: [
      { name: '鸡蛋',   quantity: 2, unit: '个', isMain: true },
      { name: '胡萝卜', quantity: 1, unit: '根', isMain: true },
      { name: '盐',     quantity: 2, unit: 'g', isMain: false },
      { name: '食用油', quantity: 10, unit: 'ml', isMain: false },
    ],
    steps: [
      '胡萝卜擦丝，鸡蛋打散',
      '热锅下油炒蛋盛出',
      '下胡萝卜丝炒软，倒回鸡蛋，加盐',
    ],
    tags: ['清淡', '快手', '早餐', '富含胡萝卜素'],
    note: '颜色好看，营养加分',
  },
  {
    id: 'rec_010',
    name: '蒜蓉炒虾',
    mealType: 'dinner',
    cuisine: '粤菜',
    difficulty: 'medium',
    prepTime: 18,
    calories: 200,
    servings: 1,
    ingredients: [
      { name: '虾',     quantity: 200, unit: 'g',  isMain: true },
      { name: '蒜',     quantity: 4,   unit: '瓣', isMain: false },
      { name: '生抽',   quantity: 8,   unit: 'ml', isMain: false },
      { name: '料酒',   quantity: 10,  unit: 'ml', isMain: false },
      { name: '食用油', quantity: 15,  unit: 'ml', isMain: false },
      { name: '姜',     quantity: 2,   unit: '片', isMain: false },
    ],
    steps: [
      '虾去虾线，加料酒腌制 5 分钟',
      '热锅下油爆香姜蒜末',
      '下虾煎至两面变红，加生抽快炒',
    ],
    tags: ['清淡', '高蛋白', '宴客'],
    note: '虾要尽快食用',
  },
  {
    id: 'rec_011',
    name: '醋溜土豆丝',
    mealType: 'lunch',
    cuisine: '家常',
    difficulty: 'medium',
    prepTime: 18,
    calories: 200,
    servings: 1,
    ingredients: [
      { name: '土豆',  quantity: 200, unit: 'g',  isMain: true },
      { name: '醋',    quantity: 10,  unit: 'ml', isMain: false },
      { name: '生抽',  quantity: 5,   unit: 'ml', isMain: false },
      { name: '蒜',    quantity: 2,   unit: '瓣', isMain: false },
      { name: '盐',    quantity: 2,   unit: 'g', isMain: false },
      { name: '食用油', quantity: 10, unit: 'ml', isMain: false },
    ],
    steps: [
      '土豆切细丝，冲水去淀粉',
      '热锅下油爆香蒜末',
      '下土豆丝大火快炒，沿锅边淋醋',
      '加生抽、盐调味出锅',
    ],
    tags: ['酸口', '快手', '主食替代'],
    note: '冲水是脆的关键',
  },
  {
    id: 'rec_012',
    name: '番茄蛋花汤',
    mealType: 'dinner',
    cuisine: '家常',
    difficulty: 'easy',
    prepTime: 12,
    calories: 130,
    servings: 2,
    ingredients: [
      { name: '番茄',  quantity: 1, unit: '个', isMain: true },
      { name: '鸡蛋',  quantity: 2, unit: '个', isMain: true },
      { name: '盐',    quantity: 2, unit: 'g',  isMain: false },
      { name: '醋',    quantity: 3, unit: 'ml', isMain: false },
      { name: '食用油', quantity: 5, unit: 'ml', isMain: false },
    ],
    steps: [
      '番茄切丁，鸡蛋打散',
      '热锅下油炒番茄出汁，加水煮开',
      '淋蛋液，蛋花浮起加盐和几滴醋',
    ],
    tags: ['清淡', '汤品', '快手'],
    note: '晚餐配汤轻盈',
  },
]

export const SEED_PREFERENCE = {
  tasteTags: ['清淡', '快手'],
  avoidTags: ['麻辣'],
  avoidIngredients: [],
  mealsPerDay: 3,
  calorieTarget: 1800,
  nutritionFocus: ['高蛋白'],
  preferUseExpiring: true,
  cuisinePreference: ['家常', '粤菜'],
}
